info = {
    legal = ['Cape Verde', 'Central African Republic', 'Chad', 'Congo', 'Côte d’Ivoire', 'Democratic Republic of Congo', 'Djibouti', 'Egypt', 'Equatorial Guinea', 'Gabon', 'Guinea-Bissau', 'Lesotho', 'Madagascar', 'Mali', 'Mozambique', 'Niger', 'Rwanda', 'São Tome & Principe', 'Seychelles', 'South Africa', 'Bahrain', 'Cambodia', 'China', 'East Timor', 'Indonesia', 'Israel', 'Japan', 'Jordan', 'Kazakhstan', 'Kyrgyzstan', 'Laos', 'Mongolia', 'Nepal', 'North Korea', 'Philippines', 'South Korea', 'Taiwan', 'Tajikistan', 'Thailand', 'Vietnam', 'West Bank in the Occupied Palestinian Territory', 'Albania', 'Andorra', 'Armenia', 'Austria', 'Azerbaijan', 'Belarus', 'Belgium', 'Bosnia and Herzegovina', 'Bulgaria', 'Croatia', 'Cyprus', 'Czech Republic', 'Denmark', 'Estonia', 'Finland', 'France', 'Georgia', 'Germany', 'Greece', 'Hungary', 'Iceland', 'Ireland', 'Italy', 'Kosovo', 'Latvia', 'Liechtenstein', 'Lithuania', 'Luxembourg', 'Macedonia (FYROM)', 'Malta', 'Moldova', 'Monaco', 'Montenegro', 'Netherlands', 'Norway', 'Poland', 'Portugal', 'Romania', 'Russia', 'San Marino', 'Serbia', 'Slovakia', 'Slovenia', 'Spain', 'Sweden', 'Switzerland', 'Turkey', 'Ukraine', 'United Kingdom (and associates)', 'Argentina', 'Bahamas', 'Belize', 'Bolivia', 'Brazil', 'Costa Rica', 'Chile', 'Colombia', 'Cuba', 'Dominican Republic', 'Ecuador', 'El Salvador, Guatemala', 'Haiti', 'Honduras', 'Mexico', 'Nicaragua', 'Panama', 'Paraguay', 'Peru', 'Suriname', 'Uruguay', 'Venezuela', 'Canada', 'United States', 'Australia', 'Fiji', 'Marshall Islands', 'Micronesia', 'New Zealand', 'Nauru', 'Palau', 'Vanuatu']
    1M-2Y = ['Burundi', 'Liberia', 'Mauritania', 'Zimbabwe', 'Bhutan', 'Iraq', 'Lebanon', 'Singapore', 'Turkmenistan', 'Lithuania', 'Russia']
    3Y-7Y = ['Algeria', 'Angola', 'Botswana', 'Cameroon', 'Comoros', 'Egypt', 'Ghana', 'Guinea', 'Libya', 'Mauritius', 'Morocco', 'Senegal', 'Somalia', 'Togo', 'Tunisia', 'Kuwait', 'Qatar', 'Syria', 'Uzbekistan', 'St Kitts & Nevis', 'Samoa']
    8Y-13Y = ['Gambia', 'Kenya', 'Malawi', 'Nigeria', 'Sierra Leone', 'South Sudan', 'Sudan', 'Swaziland', 'Afghanistan', 'Bangladesh', 'Brunei Darussalam', 'Gaza', 'Malaysia', 'Myanmar', 'Pakistan', 'Sri Lanka', 'United Arab Emirates', 'Dominica', 'Grenada', 'Jamaica', 'St Vincent & the Grenadines', 'Cook Islands', 'Kiribati', 'Papua New Guinea', 'Solomon Islands', 'Tonga', 'Tuvalu']
    14Y-Life = ['Eritrea', 'Ethiopia', 'Tanzania', 'Uganda', 'Zambia', 'India', 'South Sumatra and Aceh Provinces (Indonesia)', 'Maldives', 'Oman', 'Antigua and Barbuda', 'Barbados', 'Guyana', 'St Lucia', 'Trinidad and Tobago']
    death = ['Mauritania', 'Nigeria', 'Somalia', 'Sudan', 'Afghanistan', 'Iraq', 'Iran', 'Pakistan', 'Qatar', 'Saudi Arabia', 'Syria', 'United Arab Emirates', 'Yemen']

}
#illegal = D11300
#legal = 139E0C
#iffy = EB9707
#death = 000000

